### ISSUE TITLE
An internal error occurred due to a bug in either zc.buildout or in a recipe being used

### ISSUE THREAD

**Issue by ggkitsas** [rvanlaar/djangorecipe#96]
Hello,

I am currently working on a project that uses buildout during setup.
I am getting the following error when invoking `./bin/buildout` :
```
While:
  Installing.
  Getting section django.
  Initializing section django.
  Installing recipe djangorecipe.
  Getting distribution for 'Django==1.8.13'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/<path>/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/<path>/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 680, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/<path>/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 1274, in __getitem__
    options._initialize()
  File "/home/<path>/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 1382, in _initialize
    self.initialize()
  File "/home/<path>/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 1388, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/<path>/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/buildout.py", line 1338, in _install_and_load
    allow_hosts=buildout._allow_hosts
  File "/home/<path>/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "/home/<path>/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/easy_install.py", line 714, in install
    for dist in self._get_dist(req, ws):
  File "/home/<path>/eggs/zc.buildout-2.9.4-py2.7.egg/zc/buildout/easy_install.py", line 570, in _get_dist
    dist = self._env.best_match(requirement, ws)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1111, in best_match
    dist = working_set.find(req)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 715, in find
    raise VersionConflict(dist, req)
VersionConflict: (Django 1.11.4 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('Django==1.8.13'))
```
I have also created an [issue](https://github.com/buildout/buildout/issues/411) to the [buildout project](https://github.com/buildout/buildout).
Not sure what else shall I share here since I am new user of buildout and django.

Thank you!

**Comment by reinout** [comment]
Hi!

See the replies on the buildout ticket.
Best solution: remove the globally installed django.

Problem is that djangorecipe wants to make sure you've got django installed *before* the regular buildout package isolation kicks in. Bit of a design decision.

Anyway, we've been using djangorecipe for 7 years. If you don't have a globally installed django, it works like a charm :-)

**Comment by ggkitsas** [comment]
Thanks, that solved the issue.
